# Generated by Django 4.1.3 on 2023-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolldata', '0003_rename_enroll_enrollformdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enrolldata',
        ),
        migrations.AlterField(
            model_name='enrollformdata',
            name='photo',
            field=models.ImageField(default='', upload_to='static/studentimage'),
        ),
    ]
