# Generated by Django 4.1.7 on 2023-07-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolldata', '0002_enroll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enroll',
            new_name='EnrollFormData',
        ),
    ]
